### ISSUE TITLE
not loading .qraphql files with raw-loader

### ISSUE THREAD

**Issue by samithf** [FrontendMasters/api-design-node-v2#5]
Getting following error when importing .graphql files

export * as userType from './user.graphql'

```
Error: Cannot find module 'graphql'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

webpack

```
{
      test: /\.(graphql|gql)$/,
      exclude: /node_modules/,
      use: {
         loader: 'raw-loader'
        }
}
```
 **'raw-loader'** version is ^0.5.1

How to solve this?

**Comment by Hendrixer** [comment]
You shouldn't be exporting from a `.graphql` file. Its not a module, and will be imported as a string and converted to a module by webpack.

**Comment by Hendrixer** [comment]
also, for that error, looks like you need to install `graphql`
